global:
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'alertas@sistema.local'
  smtp_require_tls: false

route:
  receiver: email-alerts
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: email-alerts
    email_configs:
      - to: 'admin@sistema.local'
        from: 'alertas@sistema.local'
        send_resolved: true
