server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-app-log
    static_configs:
      - targets: [""]
        labels:
          job: app-log
          log_type: application
          __path__: /app/log/app-*.log

  - job_name: audit-log
    static_configs:
      - targets: [""]
        labels:
          job: audit-log
          log_type: audit
          __path__: /app/log/audit-*.log
