server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[^/]+)/'
      - replace:
          expression: /var/lib/docker/containers/(?P<container_id>[^/]+)/
          source: filename
          replace: '$container_id'
      - docker:
          source: container_id
      - labels:
          container_id:
          container_name:
